title: Unna Engenharia e Construção
email: unna@unna.eng.br
url: 'https://unna.eng.br'
baseurl: ''
description: >-
  h2: Para o cliente final e arquitetos
  set: Administração e gerenciamento de obras residenciais e comerciais.
       Planejamento de sua obra desde a fundação até a entrega final.

  h2: Para construtoras
  set:  Gestão de equipes multidisciplinares para a sua obra. Não se preocupe com orçamentos e contratação de serviços.
        Fornecimento de equipe para execução de serviços civis, de elétrica, hidráulica e demais necessários para seu empreendimento.
        Diferencial de outras empresas, pois nossa equipe técnica, composta por engenheiros, acompanha cada etapa do serviço, evitando falhas comuns em outras empresas que fornecem mão de obra terceirizada.
plugins:
  - jekyll-admin
  - jekyll-sitemap
markdown: kramdown
permalink: /:title:output_ext
lang: pt-br
author: Emerson Leite
posts:
  date_format: '%b %-d, %Y'
background:
  intro-bkg: /img/building-wallpapers-28464-2708651.jpg
color:
  primary-dark: '#fff'
  font-color: '#000'
  font-btn-color: '#fff'
  btn-bkg: '#059c00'
  about-bkg: '#fff'
  footer-bkg: '#000'
  download-bkg: '#000'
font-nav-color: '#059c00'
font-intro-color: '#000'
fontFamily:
  font-family: Arial



